helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update

helm install ingress-nginx ingress-nginx/ingress-nginx \
  --namespace ingress-nginx --create-namespace \
  --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"="true" \
  --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal-subnet"="aks" \
  --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-pls-create"="true" \
  --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-pls-visibility"="*" \
  --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-pls-auto-approval"="3f4307f4-ae2b-4a54-a328-4564262560d1" \
  --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-pls-ip-configuration-ip-address"="10.225.0.60" \
  --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-pls-ip-configuration-ip-address-count"="1" \
  --set controller.service.loadBalancerIP="10.225.0.50"