apiVersion: v1
kind: Service
metadata:
  name: weatherapp-ui
spec:
  selector:
    app.kubernetes.io/name: weatherapp-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP