apiVersion: v1
kind: Service
metadata:
  name: weatherapp-auth
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: weatherapp-auth
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000